POST  http://localhost:3000/api/service
Content-Type: application/json

{
    "nome": "Service 1",
    "descricao": "alguma descricao",
    "orcamento": 1500,
    "img": "https://www.google.com/url?sa=i&url=https%3A%2F%2Ftwitter.com%2FIMG&psig=AOvVaw3cGn7_RJcCl_uP9RnfCfnS&ust=1707431112290000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCKD7luWimoQDFQAAAAAdAAAAABAE"

}